import { cn } from "@/lib/utils";
import { Indicator } from "@/ui/indicator";

import "@/styles/globals.css";

import localFont from "next/font/local";

const fontSans = localFont({
  src: "../assets/fonts/Inter.var.woff2",
  display: "block",
  variable: "--font-sans",
});

const fontMono = localFont({
  src: "../assets/fonts/Jack-Regular.woff2",
  display: "block",
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "min-h-screen flex flex-col bg-background font-sans antialiased",
          fontSans.variable,
          fontMono.variable
        )}
      >
        <div className="flex-1 flex flex-col">{children}</div>
        <Indicator />
      </body>
    </html>
  );
}
