import { Indicator } from "@/components/ui/indicator";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import localFont from "next/font/local";

const fontSans = localFont({
  src: "../assets/fonts/Inter.var.woff2",
  variable: "--font-sans",
});

const fontMono = localFont({
  src: "../assets/fonts/Jack-Regular.woff2",
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "flex min-h-screen flex-col bg-background font-sans antialiased",
          fontSans.variable,
          fontMono.variable
        )}
      >
        <div className="flex flex-1 flex-col">{children}</div>
        <Indicator />
      </body>
    </html>
  );
}
