import { cn } from "@/lib/utils";

import "@/styles/globals.css";

import localFont from "next/font/local";

const fontSans = localFont({
  src: "../../assets/fonts/Inter.var.woff2",
  variable: "--font-sans",
});

const fontMono = localFont({
  src: "../../assets/fonts/Jack-Regular.woff2",
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontMono.variable
        )}
      >
        <div className="relative flex min-h-screen flex-col">
          <div className="fixed top-0 w-screen"></div>
          <div className="flex-1 border border-red-500">{children}</div>
        </div>
      </body>
    </html>
  );
}
