import { Indicator } from "@/components/ui/indicator";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import localFont from "next/font/local";
import "react-data-grid/lib/styles.css";

const fontSans = localFont({
  src: "../../assets/fonts/Inter.var.woff2",
  display: "swap",
  variable: "--font-sans",
});

const fontMono = localFont({
  src: "../../assets/fonts/Jack-Regular.woff2",
  display: "swap",
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "min-h-screen flex-col bg-background font-sans antialiased",
          fontSans.variable,
          fontMono.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
        <Indicator />
      </body>
    </html>
  );
}
